services:
  rustdeskserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rustdeskserver
    stdin_open: true
    tty: true
    ports:
      - 21115-21119:21115-21119/tcp
      - 8000:8000/tcp
      - 21116:21116/udp
    volumes:
      - rustdesk:/opt/rustdesk
      - gohttp:/opt/gohttp
    restart: unless-stopped
    secrets:
      - http_user
      - http_pass

secrets:
  http_user:
    file: ./http_user.txt
  http_pass:
    file: ./http_pass.txt
