services:
  rustdeskserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rustdeskserver
    stdin_open: true
    tty: true
    ports:
      - 21115-21119:21115-21119
      - 8000
      - 21116/udp
    restart: unless-stopped
    secrets:
      - http_user
      - http_pass

secrets:
  http_user:
    file: ./http_user.txt
  http_pass:
    file: ./http_pass.txt
